In [13]:
import yfinance as yf  #access historical market data
import pandas as pd

In [ ]:
ticker_symbol = 'AAPL'
ticker = yf.Ticker(ticker_symbol)
print(ticker)

In [34]:
data = yf.download(
                tickers='AMZN', 
                start="2018-01-01", 
                end="2023-12-31",
                progress= False,
                threads=False
                )

C:\Users\M R Mafi\AppData\Local\Temp\ipykernel_5792\3102447061.py:1: FutureWarning: YF.download() has changed argument auto_adjust default to True
  data = yf.download(

In [35]:
data.isnull().sum()

Price   Ticker
Close   AMZN      0
High    AMZN      0
Low     AMZN      0
Open    AMZN      0
Volume  AMZN      0
dtype: int64

In [36]:
data.duplicated().sum()

np.int64(0)

In [29]:
data = data.drop_duplicates(keep='first')
data = data.ffill()

In [37]:
data.head()

Price           Close       High        Low       Open    Volume
Ticker           AMZN       AMZN       AMZN       AMZN      AMZN
Date
2018-01-02  59.450500  59.500000  58.525501  58.599998  53890000
2018-01-03  60.209999  60.274502  59.415001  59.415001  62176000
2018-01-04  60.479500  60.793499  60.233002  60.250000  60442000
2018-01-05  61.457001  61.457001  60.500000  60.875500  70894000
2018-01-08  62.343498  62.653999  61.601501  61.799999  85590000

In [21]:
df = pd.DataFrame(data)
df.head()

Price           Close       High        Low       Open     Volume
Ticker           AAPL       AAPL       AAPL       AAPL       AAPL
Date
2018-01-02  40.380993  40.390372  39.677736  39.888715  102223600
2018-01-03  40.373966  40.917820  40.310676  40.444293  118071600
2018-01-04  40.561501  40.664645  40.338803  40.446634   89738400
2018-01-05  41.023312  41.110045  40.566195  40.657619   94640000
2018-01-08  40.870937  41.166304  40.772478  40.870937   82271200

In [26]:
import yfinance as yf
import pandas as pd

data = yf.download('AAPL', start='2018-01-01', end='2023-12-31', progress=False, threads=False)
print(type(data))   # should be <class 'pandas.core.frame.DataFrame'>
print(data.head())  # should display first 5 rows

<class 'pandas.core.frame.DataFrame'>
Price           Close       High        Low       Open     Volume
Ticker           AAPL       AAPL       AAPL       AAPL       AAPL
Date
2018-01-02  40.380993  40.390372  39.677736  39.888715  102223600
2018-01-03  40.373966  40.917820  40.310676  40.444293  118071600
2018-01-04  40.561501  40.664645  40.338803  40.446634   89738400
2018-01-05  41.023312  41.110045  40.566195  40.657619   94640000
2018-01-08  40.870937  41.166304  40.772478  40.870937   82271200

C:\Users\M R Mafi\AppData\Local\Temp\ipykernel_5792\1514944821.py:4: FutureWarning: YF.download() has changed argument auto_adjust default to True
  data = yf.download('AAPL', start='2018-01-01', end='2023-12-31', progress=False, threads=False)